/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicSrcBasicTitle: typeof import('./../components/Basic/src/BasicTitle.vue')['default']
    CodeEditor: typeof import('./../components/codeEditor/index.vue')['default']
    Content: typeof import('./../components/Content/index.vue')['default']
    DescriptionsSrc: typeof import('./../components/Descriptions/src/index.vue')['default']
    FormSrc: typeof import('./../components/Form/src/index.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Icon: typeof import('./../components/Icon/index.vue')['default']
    IconsIconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    JsonView: typeof import('./../components/JsonView/index.vue')['default']
    ModalSrc: typeof import('./../components/Modal/src/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSwitch: typeof import('naive-ui')['NSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TableSrcBasicTable: typeof import('./../components/Table/src/BasicTable.vue')['default']
    TableSrcComponentsTableHeader: typeof import('./../components/Table/src/components/TableHeader.vue')['default']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
    WindowUtils: typeof import('./../components/windowUtils/index.vue')['default']
  }
}
